
package com.example.nicoletours.common

const val LOCATION = "name"
const val ATRACTION1 = "atraction1"
const val ATRACTION2= "atraction2"
const val ATRACTION3 = "atraction3"
const val ATRACTION4 = "atraction4"
const val ATRACTION5 = "atraction5"
const val ATRACTION6 = "atraction6"
const val ATRACTION7 = "atraction7"
const val ATRACTION8 = "atraction8"
const val ATRACTION9 = "atraction9"
const val ATRACTION10 = "atraction10"
const val ATRACTION11 = "atraction11"
const val ATRACTION12 = "atraction12"
const val ATRACTION13 = "atraction13"
const val ATRACTION14 = "atraction14"
const val COST_ATRACTION1 = "costAtraction1"
const val COST_ATRACTION2 = "costAtraction2"
const val COST_ATRACTION3 = "costAtraction3"
const val COST_ATRACTION4 = "costAtraction4"
const val COST_ATRACTION5 = "costAtraction5"
const val COST_ATRACTION6 = "costAtraction6"
const val COST_ATRACTION7 = "costAtraction7"
const val COST_ATRACTION8 = "costAtraction8"
const val COST_ATRACTION9 = "costAtraction9"
const val COST_ATRACTION10 = "costAtraction10"
const val COST_ATRACTION11 = "costAtraction11"
const val COST_ATRACTION12 = "costAtraction12"
const val COST_ATRACTION13 = "costAtraction13"
const val COST_ATRACTION14 = "costAtraction14"
const val LOCATION_IMAGE1 = "image1"
const val LOCATION_IMAGE2 = "image2"